{
 "title": "Car Valuation Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(movingAverage(stats.car_valuation_service.predict_price.request_status.error.count, 50), movingAverage(sumSeries(stats.car_valuation_service.predict_price.request_status.*.count), 50)), 'Error rate')"
    }
   ]
  },
  { "title": "Service rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "alias(sum(scale(movingAverage(stats.car_valuation_service.predict_price.request_status.error.count, 50), 60), #A), 'RPM')",
     "targetFull": "alias(sum(scale(movingAverage(stats.car_valuation_service.predict_price.request_status.error.count, 50), 60), alias(scale(movingAverage(stats.car_valuation_service.predict_price.request_status.success.count, 50), 60), 'RPM')), 'RPM')"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Error rate')",
     "targetFull": "alias(divideSeries(movingAverage(stats.car_valuation_service.predict_price.request_status.error.count, 50), movingAverage(sumSeries(stats.car_valuation_service.predict_price.request_status.*.count), 50)), 'Error rate')"
    }
   ]
  },
  { "title": "Service timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Inference timings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "alias(movingAverage(stats.timers.car_valuation_service.predict_price.timing.inference_time.median, 10), 'inference time median')"
    },
    {
     "target": "alias(movingAverage(stats.timers.car_valuation_service.predict_price.timing.inference_time.upper_90, 10), 'inference time upper 90')"
    }
   ]
  }
 ]
}